// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoV2zSU3tyvQqc_6mLi17SNseZPdR-JZc',
    appId: '1:380884727756:web:39279e792a39209d51cf69',
    messagingSenderId: '380884727756',
    projectId: 'deaon-c7671',
    authDomain: 'deaon-c7671.firebaseapp.com',
    storageBucket: 'deaon-c7671.appspot.com',
    measurementId: 'G-Z55HPG0F65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYmbzpCsSPXZ0VkGvRiltWIOesgKC8sio',
    appId: '1:380884727756:android:56da3f96835c4e2351cf69',
    messagingSenderId: '380884727756',
    projectId: 'deaon-c7671',
    storageBucket: 'deaon-c7671.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr96quxVVbIbafg6gcLlPkxjsMMjToTPk',
    appId: '1:380884727756:ios:ac9d41093940cc4e51cf69',
    messagingSenderId: '380884727756',
    projectId: 'deaon-c7671',
    storageBucket: 'deaon-c7671.appspot.com',
    iosClientId: '380884727756-dd2ad2kv88th1un5980dvmhqklbcp10r.apps.googleusercontent.com',
    iosBundleId: 'com.example.deaonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr96quxVVbIbafg6gcLlPkxjsMMjToTPk',
    appId: '1:380884727756:ios:115ab47c518941b051cf69',
    messagingSenderId: '380884727756',
    projectId: 'deaon-c7671',
    storageBucket: 'deaon-c7671.appspot.com',
    iosClientId: '380884727756-6q309nf0d8t20qu1kkoj40t5n0b9os3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.deaonApp.RunnerTests',
  );
}
